service: companion-worker
provider:
  name: aws
  stage: prod
  runtime: nodejs12.x
    
functions:
  app:
    handler: src/server.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8080
